#!/bin/bash
LAW="$1"
DEST=../txt
COL=9000
echo "converting $LAW to txt($COL) => $DEST"

cd $LAW/clean/
mkdir -p $DEST


for i in $( ls *.html ); do
#    w3m $i -cols $COL -dump >$DEST/$i-w3m.txt
#    lynx $i -width $COL -dump >$DEST/$i-lynx.txt
#    links $i -width $COL -dump >$DEST/$i.txt
    elinks $i -no-numbering -no-references -dump-width $COL -dump >$DEST/$i.txt
done

cd ..
python3 ../clean_whitespace.py txt/
echo "done"
