#!/bin/bash
LAW="$1"
DEST=txt
COL=9000

if [ "$LAW" == "cl-p" ]; then
    # cl-p has tables that render horribly with long width
    COL=100
fi
echo "converting $LAW to txt($COL) => $DEST"

cd $LAW/
mkdir -p $DEST/
cd clean/


for i in $( ls *.html ); do
#    w3m $i -cols $COL -dump >$DEST/$i-w3m.txt
#    lynx $i -width $COL -dump >$DEST/$i-lynx.txt
#    links $i -width $COL -dump >$DEST/$i.txt
    elinks $i -no-numbering -no-references -dump-width $COL -dump >../$DEST/$i.txt
done

cd ..
python3 ../clean_leadspaces.py $DEST/
rm $DEST/*.tmp
echo "done"
